package kmm.modulos.exemplos.apicultura.colmeia.views;

import java.awt.Dimension;
import kmm.lib.connection.KMMConnection;
import kmm.lib.database.controls.KMMDataSetAbstract;
import kmm.padroes.cadastro.filho.CadastroFilhoPadrao;

/**
 *
 * @author cristofer
 */
public class FormCadastroColmeiaAbelha extends CadastroFilhoPadrao {

   public FormCadastroColmeiaAbelha(KMMConnection connection, KMMDataSetAbstract dataset) throws Exception {
      super(connection);
      initComponents();
      setDataset(dataset);
      preencheComboBox();
      configDataset();
      configTela();
   }

   @Override
   public String getTitle() {
      return "";
   }
   
   private void preencheComboBox() throws Exception {
      
   }
   
   private void configDataset() throws Exception {
      
   }

   private void configTela(){
      setPreferredSize(new Dimension(1024, 768));
      setMinimumSize(new Dimension(1024, 768));
   }

   /**
    * This method is called from within the constructor to initialize the form.
    * WARNING: Do NOT modify this code. The content of this method is always
    * regenerated by the Form Editor.
    */
   @SuppressWarnings("unchecked")
   // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
   private void initComponents() {

      jPanelPrincipal = new javax.swing.JPanel();
      jExtLabel1 = new kmm.componentes.controle.label.JExtLabel();
      jExtLabel2 = new kmm.componentes.controle.label.JExtLabel();
      jExtLabel3 = new kmm.componentes.controle.label.JExtLabel();
      jExtLabel4 = new kmm.componentes.controle.label.JExtLabel();
      jExtNumberField1 = new kmm.componentes.controle.numberfield.JExtNumberField();
      jExtComboBox1 = new kmm.componentes.controle.combobox.JExtComboBox();
      jExtTextField1 = new kmm.componentes.controle.textfield.JExtTextField();
      jExtNumberField2 = new kmm.componentes.controle.numberfield.JExtNumberField();
      jExtLabel5 = new kmm.componentes.controle.label.JExtLabel();

      jPanelPrincipal.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

      jExtLabel1.setText("Número:");

      jExtLabel2.setText("Nome:");

      jExtLabel3.setText("Produção individual:");

      jExtLabel4.setText("Modalidade:");

      jExtNumberField1.setText("jExtNumberField1");

      jExtTextField1.setText("jExtTextField1");

      jExtNumberField2.setText("jExtNumberField2");

      jExtLabel5.setText("ml/dia");

      javax.swing.GroupLayout jPanelPrincipalLayout = new javax.swing.GroupLayout(jPanelPrincipal);
      jPanelPrincipal.setLayout(jPanelPrincipalLayout);
      jPanelPrincipalLayout.setHorizontalGroup(
         jPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(jPanelPrincipalLayout.createSequentialGroup()
            .addContainerGap()
            .addGroup(jPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addComponent(jExtLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addComponent(jExtLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addComponent(jExtLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addComponent(jExtLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(jPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addComponent(jExtTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
               .addGroup(jPanelPrincipalLayout.createSequentialGroup()
                  .addGroup(jPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                     .addComponent(jExtComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                     .addComponent(jExtNumberField2, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                     .addGroup(jPanelPrincipalLayout.createSequentialGroup()
                        .addComponent(jExtNumberField1, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jExtLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                  .addGap(0, 274, Short.MAX_VALUE)))
            .addContainerGap())
      );
      jPanelPrincipalLayout.setVerticalGroup(
         jPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(jPanelPrincipalLayout.createSequentialGroup()
            .addContainerGap()
            .addGroup(jPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
               .addComponent(jExtLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addComponent(jExtNumberField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(jPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
               .addComponent(jExtLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addComponent(jExtTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(jPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
               .addComponent(jExtLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addComponent(jExtNumberField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addComponent(jExtLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(jPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
               .addComponent(jExtLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addComponent(jExtComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addContainerGap(15, Short.MAX_VALUE))
      );

      javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getPanelConteudo());
      getPanelConteudo().setLayout(layout);
      layout.setHorizontalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(jPanelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addContainerGap())
      );
      layout.setVerticalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(jPanelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
      );
   }// </editor-fold>//GEN-END:initComponents
   // Variables declaration - do not modify//GEN-BEGIN:variables
   private kmm.componentes.controle.combobox.JExtComboBox jExtComboBox1;
   private kmm.componentes.controle.label.JExtLabel jExtLabel1;
   private kmm.componentes.controle.label.JExtLabel jExtLabel2;
   private kmm.componentes.controle.label.JExtLabel jExtLabel3;
   private kmm.componentes.controle.label.JExtLabel jExtLabel4;
   private kmm.componentes.controle.label.JExtLabel jExtLabel5;
   private kmm.componentes.controle.numberfield.JExtNumberField jExtNumberField1;
   private kmm.componentes.controle.numberfield.JExtNumberField jExtNumberField2;
   private kmm.componentes.controle.textfield.JExtTextField jExtTextField1;
   private javax.swing.JPanel jPanelPrincipal;
   // End of variables declaration//GEN-END:variables
}
